version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
  - generator: "Visual Studio 15"
    config: Release
    platform: Win32
    outdir: Release
    arch: vs2017-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

  - generator: "Visual Studio 14"
    config: Release
    platform: Win32
    outdir: Release
    arch: vs2015-x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - git config --global core.autocrlf input

build_script:
  - msbuild src\spcmem.sln /t:build /p:Configuration=%config%;Platform="%platform%" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: $env:gitrev = git describe --tags
  - ps: $env:my_version = "$env:gitrev"
  - set package_name=spcmem-%my_version%-%arch%
  - copy src\%outdir%\spcmem.exe .
  - 7z a -mx9 %package_name%.7z spcmem.exe README.md README_ja.md LICENSE.txt

artifacts:
  - path: $(package_name).7z
    name: $(arch)
